package com.ygb.test.mapper;

import com.ygb.test.model.User;

/**
 * Created by yangguobiao on 2017/7/30.
 */
public interface UserMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user
   *
   * @mbggenerated
   */
  int insert(User record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user
   *
   * @mbggenerated
   */
  int insertSelective(User record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user
   *
   * @mbggenerated
   */
  User selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(User record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(User record);
}
